// priority: 0

// Duplicate fluids or ones removed by the modpack.
const hiddenFluids = [
  'cofh_core:honey',
  'cofh_core:potion',
  'createarmory:molten_brass',
  'create_things_and_misc:diluted_bonemeal',
  'pneumaticcraft:oil',
  'pneumaticcraft:memory_essence',
  'sophisticatedcore:xp_still',
  'thermal:creosote',
  'thermal:crude_oil',
  'thermal:heavy_oil',
  'thermal:light_oil',
  'thermal:refined_fuel',
  'tfmg:liquid_plastic',
  'tfmg:gasoline',
  'tfmg:diesel',
  'tfmg:kerosene',
  'tfmg:naphtha',
  'tfmg:heavy_oil',
  'tfmg:lubrication_oil',
  'tfmg:cooling_fluid',
]

JEIEvents.addItems((e) => {
  e.add('thermal:drill_head')
  e.add('thermal:saw_blade')
  e.add('apotheosis:ancient_material')
})

JEIEvents.hideItems((e) => {
  // Defined in startup_scripts/removedRecipes.js
  global.removedRecipes.forEach((r) => {
    if (r.output) {
      e.hide(r.output)
    }
  })

  // Hide all the buckets for unused fluids.
  hiddenFluids.forEach((fluid) => {
    e.hide(`${fluid}_bucket`)
  })

  // Hide intermediate mechanism items.
  e.hide('kubejs:incomplete_andesite_mechanism')
  e.hide('kubejs:incomplete_copper_mechanism')
  e.hide('kubejs:incomplete_source_mechanism')
  e.hide('kubejs:incomplete_logistics_mechanism')
  e.hide('kubejs:incomplete_crystalline_mechanism')
})

JEIEvents.addFluids((e) => {
  // Add the Create awkward potion so custom brewing recipes can be looked up.
  e.add(
    Fluid.of('create:potion').withNBT({
      Bottle: 'REGULAR',
      Potion: 'minecraft:awkward',
    })
  )
})

JEIEvents.hideFluids((e) => {
  hiddenFluids.forEach((fluid) => {
    e.hide(fluid)
  })
})

JEIEvents.removeCategories((e) => {
  e.remove('thermal:bottler')
  e.remove('thermal:furnace')
  e.remove('thermal:brewer')
  e.remove('jumbofurnace:jumbo_smelting')
  e.remove('jumbofurnace:jumbo_furnace_upgrade')
})

// Multiple iterations through all recipe types is inefficient, but the code
// is more readable.
JEIAddedEvents.onRuntimeAvailable((e) => {
  const { recipeManager, jeiHelpers } = e.data

  // Hide all recipes generated by custom sequenced assembly past the first
  // loop. They may not necessarily all be of type create:sequenced_assembly
  // but their IDs all end in _hidejei
  jeiHelpers.allRecipeTypes.forEach((recipeType) => {
    const recipesToHide = recipeManager
      .createRecipeLookup(recipeType)
      .get()
      .filter((recipe) => {
        return (
          recipe.getId !== undefined &&
          recipe.getId().toString().endsWith('_hidejei')
        )
      })
      .toList()
    recipeManager.hideRecipes(recipeType, recipesToHide)
  })

  // Hide all anvilling recipes for Soulbound and Reactive enchantments since
  // they apply to all items and clog JEI.
  recipeManager.hideRecipes(
    'minecraft:anvil',
    recipeManager
      .createRecipeLookup('minecraft:anvil')
      .get()
      .filter((recipe) => {
        for (let input of recipe.getRightInputs()) {
          if (
            input.id === 'minecraft:enchanted_book' &&
            (input.enchantments.containsKey('ars_elemental:soulbound') ||
              input.enchantments.containsKey('ars_nouveau:reactive'))
          ) {
            return true
          }
        }
        return false
      })
      .toList()
  )
})
