// priority: 0

StartupEvents.registry('fluid', (e) => {
  e.create('molten_copper')
    .thickTexture(0xa33b1f)
    .bucketColor(0xa33b1f)
    .displayName('Molten Copper')
  e.create('molten_iron')
    .thickTexture(0xa62c2b)
    .bucketColor(0xa62c2b)
    .displayName('Molten Iron')
  e.create('molten_zinc')
    .thickTexture(0xaebda8)
    .bucketColor(0xaebda8)
    .displayName('Molten Zinc')
  e.create('molten_brass')
    .thickTexture(0xf8ca67)
    .bucketColor(0xf8ca67)
    .displayName('Molten Brass')

  e.create('molten_obsidian')
    .thickTexture(0x2f1434)
    .bucketColor(0x2f1434)
    .displayName('Molten Obsidian')

  e.create('molten_quartz')
    .thickTexture(0xd6c0bf)
    .bucketColor(0xd6c0bf)
    .displayName('Molten Nether Quartz')
  e.create('molten_diamond')
    .thickTexture(0x25ebec)
    .bucketColor(0x25ebec)
    .displayName('Molten Diamond')
  e.create('molten_emerald')
    .thickTexture(0x2cc879)
    .bucketColor(0x2cc879)
    .displayName('Molten Emerald')
  e.create('molten_lapis')
    .thickTexture(0x2c5cc8)
    .bucketColor(0x2c5cc8)
    .displayName('Molten Lapis')
  e.create('molten_redstone')
    .thickTexture(0xc82c2c)
    .bucketColor(0xc82c2c)
    .displayName('Molten Redstone')
})
